export const ARTICLE_LIST_REQUEST = 'ARTICLE_LIST_REQUEST'
export const ARTICLE_LIST_SUCCESS = 'ARTICLE_LIST_SUCCESS'
export const ARTICLE_LIST_FAIL = 'ARTICLE_LIST_FAIL'

export const ARTICLE_DETAIL_REQUEST = 'ARTICLE_DETAIL_REQUEST'
export const ARTICLE_DETAIL_SUCCESS = 'ARTICLE_DETAIL_SUCCESS'
export const ARTICLE_DETAIL_FAIL = 'ARTICLE_DETAIL_FAIL'

export const ARTICLE_RIGHT_COLUMN_REQUEST = 'ARTICLE_RIGHT_COLUMN_REQUEST'
export const ARTICLE_RIGHT_COLUMN_SUCCESS = 'ARTICLE_RIGHT_COLUMN_SUCCESS'
export const ARTICLE_RIGHT_COLUMN_FAIL = 'ARTICLE_RIGHT_COLUMN_FAIL'

export const MAIL_REQUEST = 'MAIL_REQUEST'
export const MAIL_SUCCESS = 'MAIL_SUCCESS'
export const MAIL_FAIL = 'MAIL_FAIL'

export const SEARCH_REQUEST = 'SEARCH_REQUEST'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAIL = 'SEARCH_FAIL'